In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(
     [
         [15, 32, 101],
         [np.nan, 46, 103],
         [np.nan, 52, np.nan]
     ],
     index=['A','B','C'],
     columns=['C1','C2','C3'])

In [3]:
df

     C1  C2     C3
A  15.0  32  101.0
B   NaN  46  103.0
C   NaN  52    NaN

In [4]:
df.dropna()

     C1  C2     C3
A  15.0  32  101.0

In [5]:
df.dropna(axis=1)

   C2
A  32
B  46
C  52

In [6]:
df.dropna(axis=1, thresh=2)

   C2     C3
A  32  101.0
B  46  103.0
C  52    NaN

In [7]:
df.fillna(165)

      C1  C2     C3
A   15.0  32  101.0
B  165.0  46  103.0
C  165.0  52  165.0

In [8]:
df.fillna('amira')

      C1  C2     C3
A   15.0  32  101.0
B  amira  46  103.0
C  amira  52  amira

In [9]:
df

     C1  C2     C3
A  15.0  32  101.0
B   NaN  46  103.0
C   NaN  52    NaN

In [10]:
df.fillna(df['C2'].sum())

      C1  C2     C3
A   15.0  32  101.0
B  130.0  46  103.0
C  130.0  52  130.0

In [11]:
df.fillna(df['C2'].mean())

          C1  C2          C3
A  15.000000  32  101.000000
B  43.333333  46  103.000000
C  43.333333  52   43.333333

In [12]:
df.dropna(inplace=True)

In [13]:
df

     C1  C2     C3
A  15.0  32  101.0