In [1]:
import pandas as pd
import numpy as np
from numpy.random import randn
np.random.seed(12)

In [2]:
s = pd.Series(np.random.randint(0, 7, size=10))

In [3]:
s

0    3
1    3
2    6
3    5
4    1
5    2
6    3
7    3
8    4
9    0
dtype: int32

In [9]:
df = pd.DataFrame(
     randn(6,3),
     index=['A','B','C','D','E','F'],
     columns=['C1','C2','C3'])

In [10]:
df

         C1        C2        C3
A  0.873135  0.910565  1.047646
B -1.189639 -1.240562  0.055302
C  0.212211 -0.345324  1.202163
D -2.205594 -1.080765 -0.086147
E  0.493514 -1.164466 -2.399881
F -0.610064 -2.233480  0.794752

In [12]:
df.head(2)

         C1        C2        C3
A  0.873135  0.910565  1.047646
B -1.189639 -1.240562  0.055302

In [14]:
df.tail(3)

         C1        C2        C3
D -2.205594 -1.080765 -0.086147
E  0.493514 -1.164466 -2.399881
F -0.610064 -2.233480  0.794752

In [15]:
df<=0

      C1     C2     C3
A  False  False  False
B   True   True  False
C  False   True  False
D   True   True   True
E  False   True   True
F   True   True  False

In [16]:
df_2 =df[df<=0]

In [17]:
df_2

         C1        C2        C3
A       NaN       NaN       NaN
B -1.189639 -1.240562       NaN
C       NaN -0.345324       NaN
D -2.205594 -1.080765 -0.086147
E       NaN -1.164466 -2.399881
F -0.610064 -2.233480       NaN

In [18]:
df

         C1        C2        C3
A  0.873135  0.910565  1.047646
B -1.189639 -1.240562  0.055302
C  0.212211 -0.345324  1.202163
D -2.205594 -1.080765 -0.086147
E  0.493514 -1.164466 -2.399881
F -0.610064 -2.233480  0.794752

In [19]:
df_2 =df[df['C3']>0]

In [20]:
df_2

         C1        C2        C3
A  0.873135  0.910565  1.047646
B -1.189639 -1.240562  0.055302
C  0.212211 -0.345324  1.202163
F -0.610064 -2.233480  0.794752

In [21]:
df_2 =df[(df['C3']<=0) & df['C1']>=0.3]

In [22]:
df_2

         C1        C2        C3
D -2.205594 -1.080765 -0.086147
E  0.493514 -1.164466 -2.399881

In [23]:
df_2 =df[(df['C3']<=0) | (df['C1']>=0.5)]

In [24]:
df_2

         C1        C2        C3
A  0.873135  0.910565  1.047646
D -2.205594 -1.080765 -0.086147
E  0.493514 -1.164466 -2.399881

In [25]:
df

         C1        C2        C3
A  0.873135  0.910565  1.047646
B -1.189639 -1.240562  0.055302
C  0.212211 -0.345324  1.202163
D -2.205594 -1.080765 -0.086147
E  0.493514 -1.164466 -2.399881
F -0.610064 -2.233480  0.794752

In [26]:
df_2 =df[(df['C3']<=0) | (df['C1']>=0.5)]['C2']

In [27]:
df_2

A    0.910565
D   -1.080765
E   -1.164466
Name: C2, dtype: float64

In [28]:
df_2 =df[(df['C3']<=0) | df['C1']>=0.5].loc['B']

In [29]:
df_2

C1   -1.189639
C2   -1.240562
C3    0.055302
Name: B, dtype: float64