In [1]:
import pandas as pd

In [6]:
df1 = pd.DataFrame(0,index=['X','Y','Z'],columns=['C1','C2','C3'])

In [7]:
df1

   C1  C2  C3
X   0   0   0
Y   0   0   0
Z   0   0   0

In [8]:
df1.reset_index()

  index  C1  C2  C3
0     X   0   0   0
1     Y   0   0   0
2     Z   0   0   0

In [12]:
import pandas as pd
import numpy as np
from numpy.random import randn
np.random.seed(125)

In [15]:
df= pd.DataFrame(randn(3,3),index=['X','Y','Z'], columns=['C1','C2','C3'])

In [16]:
df

         C1        C2        C3
X  2.686968 -0.883899 -0.403669
Y  0.101924  1.195981  1.172411
Z  0.169104 -0.491324 -0.829403

In [17]:
df['C1']

X    2.686968
Y    0.101924
Z    0.169104
Name: C1, dtype: float64

In [18]:
df[['C1', 'C2','C3']]

         C1        C2        C3
X  2.686968 -0.883899 -0.403669
Y  0.101924  1.195981  1.172411
Z  0.169104 -0.491324 -0.829403

In [19]:
df['C_4']= df['C1'] + df['C3']

In [20]:
df

         C1        C2        C3       C_4
X  2.686968 -0.883899 -0.403669  2.283299
Y  0.101924  1.195981  1.172411  1.274335
Z  0.169104 -0.491324 -0.829403 -0.660299

In [21]:
df['Y']

KeyError: 'Y'

In [25]:
df.loc['Y']

C1     0.101924
C2     1.195981
C3     1.172411
C_4    1.274335
Name: Y, dtype: float64

In [23]:
df

         C1        C2        C3       C_4
X  2.686968 -0.883899 -0.403669  2.283299
Y  0.101924  1.195981  1.172411  1.274335
Z  0.169104 -0.491324 -0.829403 -0.660299

In [27]:
df.iloc[0]

C1     2.686968
C2    -0.883899
C3    -0.403669
C_4    2.283299
Name: X, dtype: float64

In [28]:
df.loc[['X','Z']]

         C1        C2        C3       C_4
X  2.686968 -0.883899 -0.403669  2.283299
Z  0.169104 -0.491324 -0.829403 -0.660299

In [29]:
df.loc[['X','Z'],['C1','C2']]

         C1        C2
X  2.686968 -0.883899
Z  0.169104 -0.491324

In [30]:
df.loc['X','C3']

-0.4036689247102952

In [31]:
df3=df.drop('C_4', axis=1)

In [32]:
df3

         C1        C2        C3
X  2.686968 -0.883899 -0.403669
Y  0.101924  1.195981  1.172411
Z  0.169104 -0.491324 -0.829403

In [33]:
df

         C1        C2        C3       C_4
X  2.686968 -0.883899 -0.403669  2.283299
Y  0.101924  1.195981  1.172411  1.274335
Z  0.169104 -0.491324 -0.829403 -0.660299

In [34]:
df.drop('C_4', axis=1, inplace=True)

In [35]:
df

         C1        C2        C3
X  2.686968 -0.883899 -0.403669
Y  0.101924  1.195981  1.172411
Z  0.169104 -0.491324 -0.829403

In [36]:
df.drop('Y', axis=0, inplace=True)

In [37]:
df

         C1        C2        C3
X  2.686968 -0.883899 -0.403669
Z  0.169104 -0.491324 -0.829403

In [38]:
df.drop(['C1','C3'], axis=1, inplace=True)

In [39]:
df

         C2
X -0.883899
Z -0.491324